FROM ruby:3.3.0-slim
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev libmariadb-dev nodejs

ENV API_APP_PATH /app

RUN mkdir $API_APP_PATH
WORKDIR $API_APP_PATH

COPY ./Gemfile $API_APP_PATH
COPY ./Gemfile.lock $API_APP_PATH

RUN bundle install

COPY . .

COPY ./entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
